api_version: 2
defaults:
  auto_merge: false
  update_external_dependencies: false # TODO: enable after verifying that this repo meets the conditions
overrides:
  - dependency: rubocop-govuk
    auto_merge: true