require "plek"

module GovukPersonalisation::Urls
  # Find the GOV.UK URL for the "sign in" page
  #
  # @return [String] the URL
  def self.sign_in
    find_govuk_url(var: "SIGN_IN", application: "frontend", path: "/account")
  end

  # Find the GOV.UK URL for the "sign out" page
  #
  # @return [String] the URL
  def self.sign_out
    find_govuk_url(var: "SIGN_OUT", application: "frontend", path: "/sign-out")
  end

  # Find the GOV.UK URL for the "email manager" page
  #
  # @return [String] the URL
  def self.manage_email
    find_govuk_url(var: "SIGN_OUT", application: "email-alert-frontend", path: "/email/manage")
  end

  # Find the external URL for the "your services" page on One Login
  #
  # @return [String] the URL
  def self.one_login_your_services
    find_external_url(var: "ONE_LOGIN_YOUR_SERVICES", url: "https://#{digital_identity_domain('home')}")
  end

  def self.your_account
    one_login_your_services
  end

  # Find the external URL for the "security" page on One Login
  #
  # @return [String] the URL
  def self.one_login_security
    find_external_url(var: "ONE_LOGIN_SECURITY", url: "https://#{digital_identity_domain('home')}/security")
  end

  def self.manage
    one_login_security
  end

  def self.security
    one_login_security
  end

  # Find the external URL for the "feedback" page on One Login
  #
  # @return [String] the URL
  def self.one_login_feedback
    find_external_url(var: "ONE_LOGIN_FEEDBACK", url: "https://#{digital_identity_domain('signin')}/support?supportType=PUBLIC")
  end

  def self.feedback
    one_login_feedback
  end

  # Finds a URL on www.gov.uk.  This method is used so we can have
  # links which work both in production (where the website root is
  # returned) and in local development (where an application URL is
  # returned).
  #
  # If `GOVUK_PERSONALISATION_#{var}_URI` is in the environment, that
  # will be returned.
  #
  # Otherwise, a `www.gov.uk` URL will be returned (a `dev.gov.uk`
  # domain in development mode)
  #
  # @param var         [String] the name of the variable to look up
  # @param application [String] the name of the frontend application, passed to Plek, to use in development mode (if the env var is set, this is ignored)
  # @param path        [String] the path to use (if the env var is set this is ignored)
  #
  # @return [String] the URL
  def self.find_govuk_url(var:, application:, path:)
    value_from_env_var = ENV["GOVUK_PERSONALISATION_#{var}_URI"]
    if value_from_env_var
      value_from_env_var
    else
      plek_application_uri = Rails.env.development? ? Plek.find(application) : Plek.new.website_root
      "#{plek_application_uri}#{path}"
    end
  end

  # Finds a URL outside www.gov.uk
  #
  # If `GOVUK_PERSONALISATION_#{var}_URI` is in the environment, that
  # will be returned.
  #
  # Otherwise, an application URL generated by Plek will be returned.
  #
  # @param var [String] the name of the variable to look up
  # @param url [String] the url to default to if there is no environment variable set
  #
  # @return [String] the URL
  def self.find_external_url(var:, url:)
    ENV.fetch("GOVUK_PERSONALISATION_#{var}_URI", url)
  end

  def self.digital_identity_domain(host)
    if ["production", nil].include?(digital_identity_environment)
      "#{host}.account.gov.uk"
    else
      "#{host}.#{digital_identity_environment}.account.gov.uk"
    end
  end

  # DI/One Login's environments don't map exactly to ours - their staging points to
  # our integration and vice versa. So translate here.
  DIGITAL_IDENTITY_ENVIRONMENT_MAP = {
    "production" => "production",
    "staging" => "integration",
    "integration" => "staging",
  }.freeze

  def self.digital_identity_environment
    return ENV["DIGITAL_IDENTITY_ENVIRONMENT"] if ENV["DIGITAL_IDENTITY_ENVIRONMENT"]

    DIGITAL_IDENTITY_ENVIRONMENT_MAP[ENV["GOVUK_ENVIRONMENT"]] || ENV["GOVUK_ENVIRONMENT"]
  end
end
